"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const utils_1 = require("@medusajs/framework/utils");
const search_log_1 = require("./models/search-log");
/** Hard cap on a single query string — anything longer is junk. */
const MAX_QUERY_LEN = 100;
/** Minimum length after normalization. Anything shorter is noise. */
const MIN_QUERY_LEN = 3;
/** How far back a query can have been used to still count as "trending". */
const TRENDING_WINDOW_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
/**
 * Process-local cache for `getTrending`. The trending endpoint is
 * called on every search-bar focus / mobile-overlay open across all
 * shoppers, so we de-duplicate the DB hit aggressively. 5 minutes is
 * a good balance — popular queries don't shuffle that fast, and a
 * freshly logged query only has to wait at most 5 minutes to appear.
 *
 * Cache keyed by `limit` so the same response can serve different
 * callers that ask for different sizes (default 8, mobile drawer 12,
 * admin preview 20, etc.).
 */
const TRENDING_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes
const trendingCache = new Map();
/**
 * Normalize a raw query into the canonical form that gets stored.
 * The same input must always produce the same output so the `query`
 * column dedupes correctly:
 *
 *   - lowercase
 *   - trim
 *   - collapse runs of internal whitespace into a single space
 *   - strip control characters
 *
 * Returns an empty string when the query is unsuitable for logging
 * (too short, too long, empty).
 */
function normalizeQuery(raw) {
    if (typeof raw !== "string")
        return "";
    const cleaned = raw
        .toLowerCase()
        .replace(/[\u0000-\u001f\u007f]/g, " ")
        .replace(/\s+/g, " ")
        .trim();
    if (cleaned.length < MIN_QUERY_LEN || cleaned.length > MAX_QUERY_LEN)
        return "";
    return cleaned;
}
/**
 * `SearchLogModuleService` exposes the standard CRUD generated by
 * `MedusaService` plus two convenience methods used by the public
 * `/store/search/log` and `/store/search/trending` routes:
 *
 *   • `logQuery(raw)`     — upserts the query (lowercased + trimmed)
 *                           and increments its counter.
 *   • `getTrending(limit)` — returns the top N queries from the last
 *                           30 days, ordered by frequency.
 *
 * The frontend never talks to the underlying CRUD methods directly.
 */
class SearchLogModuleService extends (0, utils_1.MedusaService)({ SearchLog: search_log_1.SearchLog }) {
    /**
     * Idempotent increment-or-create. Safe to fire-and-forget from the
     * storefront — even if another request races us, the worst case is
     * two rows for the same normalized query, which `getTrending` would
     * still aggregate visually because both copies sort near each other.
     *
     * Bumping a query also invalidates the trending cache so the new
     * count surfaces on the next read instead of waiting for the TTL.
     */
    async logQuery(raw) {
        const query = normalizeQuery(raw);
        if (!query)
            return;
        const existing = await this.listSearchLogs({ query }, { take: 1 });
        if (existing && existing[0]) {
            await this.updateSearchLogs({
                id: existing[0].id,
                count: (existing[0].count || 0) + 1,
                last_used_at: new Date(),
            });
        }
        else {
            await this.createSearchLogs({
                query,
                count: 1,
                last_used_at: new Date(),
            });
        }
        // Invalidate trending cache so the new datapoint is visible
        // immediately on the next read instead of waiting up to 5 min.
        trendingCache.clear();
    }
    /**
     * Returns the top `limit` queries that have been logged in the last
     * 30 days, sorted by frequency (DESC). Stale queries fall off
     * naturally without needing a cron job — they just stop being
     * eligible until someone searches them again.
     *
     * Hot-path performance: this endpoint is hit on every search-bar
     * focus / mobile-overlay open. We short-circuit through a 5-minute
     * process-local cache keyed by `limit` so high-traffic stores don't
     * round-trip Postgres on every keystroke.
     */
    async getTrending(limit = 8) {
        const cap = Math.min(20, Math.max(1, Math.floor(limit) || 8));
        const cached = trendingCache.get(cap);
        if (cached && cached.expires > Date.now()) {
            return cached.value;
        }
        // Fetch a small over-sample (e.g. top 50 by count) so we still
        // have enough rows after the in-memory recency filter to satisfy
        // `cap`. We can't push the `last_used_at >= cutoff` predicate
        // through the Medusa list API cleanly, but the count index makes
        // this a very cheap top-N scan regardless.
        const overSample = Math.max(50, cap * 5);
        const rows = await this.listSearchLogs({}, {
            take: overSample,
            order: { count: "DESC" },
        });
        const cutoff = Date.now() - TRENDING_WINDOW_MS;
        const value = (rows || [])
            .filter((row) => {
            if (!row.last_used_at)
                return true;
            const t = new Date(row.last_used_at).getTime();
            return Number.isFinite(t) ? t >= cutoff : true;
        })
            .slice(0, cap)
            .map((row) => row.query);
        trendingCache.set(cap, {
            value,
            expires: Date.now() + TRENDING_CACHE_TTL_MS,
        });
        return value;
    }
}
exports.default = SearchLogModuleService;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VydmljZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uLy4uLy4uLy4uLy4uL3NyYy9tb2R1bGVzL3NlYXJjaC1sb2cvc2VydmljZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztBQUFBLHFEQUF5RDtBQUN6RCxvREFBK0M7QUFFL0MsbUVBQW1FO0FBQ25FLE1BQU0sYUFBYSxHQUFHLEdBQUcsQ0FBQTtBQUV6QixxRUFBcUU7QUFDckUsTUFBTSxhQUFhLEdBQUcsQ0FBQyxDQUFBO0FBRXZCLDRFQUE0RTtBQUM1RSxNQUFNLGtCQUFrQixHQUFHLEVBQUUsR0FBRyxFQUFFLEdBQUcsRUFBRSxHQUFHLEVBQUUsR0FBRyxJQUFJLENBQUEsQ0FBQyxVQUFVO0FBRTlEOzs7Ozs7Ozs7O0dBVUc7QUFDSCxNQUFNLHFCQUFxQixHQUFHLENBQUMsR0FBRyxFQUFFLEdBQUcsSUFBSSxDQUFBLENBQUMsWUFBWTtBQUN4RCxNQUFNLGFBQWEsR0FBRyxJQUFJLEdBQUcsRUFBZ0QsQ0FBQTtBQUU3RTs7Ozs7Ozs7Ozs7O0dBWUc7QUFDSCxTQUFTLGNBQWMsQ0FBQyxHQUFXO0lBQ2pDLElBQUksT0FBTyxHQUFHLEtBQUssUUFBUTtRQUFFLE9BQU8sRUFBRSxDQUFBO0lBQ3RDLE1BQU0sT0FBTyxHQUFHLEdBQUc7U0FDaEIsV0FBVyxFQUFFO1NBQ2IsT0FBTyxDQUFDLHdCQUF3QixFQUFFLEdBQUcsQ0FBQztTQUN0QyxPQUFPLENBQUMsTUFBTSxFQUFFLEdBQUcsQ0FBQztTQUNwQixJQUFJLEVBQUUsQ0FBQTtJQUNULElBQUksT0FBTyxDQUFDLE1BQU0sR0FBRyxhQUFhLElBQUksT0FBTyxDQUFDLE1BQU0sR0FBRyxhQUFhO1FBQUUsT0FBTyxFQUFFLENBQUE7SUFDL0UsT0FBTyxPQUFPLENBQUE7QUFDaEIsQ0FBQztBQUVEOzs7Ozs7Ozs7OztHQVdHO0FBQ0gsTUFBTSxzQkFBdUIsU0FBUSxJQUFBLHFCQUFhLEVBQUMsRUFBRSxTQUFTLEVBQVQsc0JBQVMsRUFBRSxDQUFDO0lBQy9EOzs7Ozs7OztPQVFHO0lBQ0gsS0FBSyxDQUFDLFFBQVEsQ0FBQyxHQUFXO1FBQ3hCLE1BQU0sS0FBSyxHQUFHLGNBQWMsQ0FBQyxHQUFHLENBQUMsQ0FBQTtRQUNqQyxJQUFJLENBQUMsS0FBSztZQUFFLE9BQU07UUFFbEIsTUFBTSxRQUFRLEdBQUcsTUFBTyxJQUFZLENBQUMsY0FBYyxDQUNqRCxFQUFFLEtBQUssRUFBRSxFQUNULEVBQUUsSUFBSSxFQUFFLENBQUMsRUFBRSxDQUNaLENBQUE7UUFFRCxJQUFJLFFBQVEsSUFBSSxRQUFRLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQztZQUM1QixNQUFPLElBQVksQ0FBQyxnQkFBZ0IsQ0FBQztnQkFDbkMsRUFBRSxFQUFFLFFBQVEsQ0FBQyxDQUFDLENBQUMsQ0FBQyxFQUFFO2dCQUNsQixLQUFLLEVBQUUsQ0FBQyxRQUFRLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxJQUFJLENBQUMsQ0FBQyxHQUFHLENBQUM7Z0JBQ25DLFlBQVksRUFBRSxJQUFJLElBQUksRUFBRTthQUN6QixDQUFDLENBQUE7UUFDSixDQUFDO2FBQU0sQ0FBQztZQUNOLE1BQU8sSUFBWSxDQUFDLGdCQUFnQixDQUFDO2dCQUNuQyxLQUFLO2dCQUNMLEtBQUssRUFBRSxDQUFDO2dCQUNSLFlBQVksRUFBRSxJQUFJLElBQUksRUFBRTthQUN6QixDQUFDLENBQUE7UUFDSixDQUFDO1FBRUQsNERBQTREO1FBQzVELCtEQUErRDtRQUMvRCxhQUFhLENBQUMsS0FBSyxFQUFFLENBQUE7SUFDdkIsQ0FBQztJQUVEOzs7Ozs7Ozs7O09BVUc7SUFDSCxLQUFLLENBQUMsV0FBVyxDQUFDLEtBQUssR0FBRyxDQUFDO1FBQ3pCLE1BQU0sR0FBRyxHQUFHLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxFQUFFLElBQUksQ0FBQyxHQUFHLENBQUMsQ0FBQyxFQUFFLElBQUksQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQTtRQUU3RCxNQUFNLE1BQU0sR0FBRyxhQUFhLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxDQUFBO1FBQ3JDLElBQUksTUFBTSxJQUFJLE1BQU0sQ0FBQyxPQUFPLEdBQUcsSUFBSSxDQUFDLEdBQUcsRUFBRSxFQUFFLENBQUM7WUFDMUMsT0FBTyxNQUFNLENBQUMsS0FBSyxDQUFBO1FBQ3JCLENBQUM7UUFFRCwrREFBK0Q7UUFDL0QsaUVBQWlFO1FBQ2pFLDhEQUE4RDtRQUM5RCxpRUFBaUU7UUFDakUsMkNBQTJDO1FBQzNDLE1BQU0sVUFBVSxHQUFHLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxFQUFFLEdBQUcsR0FBRyxDQUFDLENBQUMsQ0FBQTtRQUN4QyxNQUFNLElBQUksR0FBVSxNQUFPLElBQVksQ0FBQyxjQUFjLENBQ3BELEVBQUUsRUFDRjtZQUNFLElBQUksRUFBRSxVQUFVO1lBQ2hCLEtBQUssRUFBRSxFQUFFLEtBQUssRUFBRSxNQUFNLEVBQVM7U0FDaEMsQ0FDRixDQUFBO1FBRUQsTUFBTSxNQUFNLEdBQUcsSUFBSSxDQUFDLEdBQUcsRUFBRSxHQUFHLGtCQUFrQixDQUFBO1FBQzlDLE1BQU0sS0FBSyxHQUFHLENBQUMsSUFBSSxJQUFJLEVBQUUsQ0FBQzthQUN2QixNQUFNLENBQUMsQ0FBQyxHQUFRLEVBQUUsRUFBRTtZQUNuQixJQUFJLENBQUMsR0FBRyxDQUFDLFlBQVk7Z0JBQUUsT0FBTyxJQUFJLENBQUE7WUFDbEMsTUFBTSxDQUFDLEdBQUcsSUFBSSxJQUFJLENBQUMsR0FBRyxDQUFDLFlBQVksQ0FBQyxDQUFDLE9BQU8sRUFBRSxDQUFBO1lBQzlDLE9BQU8sTUFBTSxDQUFDLFFBQVEsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxJQUFJLE1BQU0sQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFBO1FBQ2hELENBQUMsQ0FBQzthQUNELEtBQUssQ0FBQyxDQUFDLEVBQUUsR0FBRyxDQUFDO2FBQ2IsR0FBRyxDQUFDLENBQUMsR0FBUSxFQUFFLEVBQUUsQ0FBQyxHQUFHLENBQUMsS0FBZSxDQUFDLENBQUE7UUFFekMsYUFBYSxDQUFDLEdBQUcsQ0FBQyxHQUFHLEVBQUU7WUFDckIsS0FBSztZQUNMLE9BQU8sRUFBRSxJQUFJLENBQUMsR0FBRyxFQUFFLEdBQUcscUJBQXFCO1NBQzVDLENBQUMsQ0FBQTtRQUVGLE9BQU8sS0FBSyxDQUFBO0lBQ2QsQ0FBQztDQUNGO0FBRUQsa0JBQWUsc0JBQXNCLENBQUEifQ==